# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.srcs/sources_1/ip/Graying_0/Graying_0.xci
# IP: The module: 'Graying_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/Graying_0/sources_1/ip/MultiplierBluex0d114/MultiplierBluex0d114.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MultiplierBluex0d114 || ORIG_REF_NAME==MultiplierBluex0d114} -quiet] -quiet

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/Graying_0/sources_1/ip/MultiplierGreenx0d587/MultiplierGreenx0d587.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MultiplierGreenx0d587 || ORIG_REF_NAME==MultiplierGreenx0d587} -quiet] -quiet

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/Graying_0/sources_1/ip/MultiplierRedx0d299/MultiplierRedx0d299.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MultiplierRedx0d299 || ORIG_REF_NAME==MultiplierRedx0d299} -quiet] -quiet

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.srcs/sources_1/ip/Graying_0/Graying_0.xci
# IP: The module: 'Graying_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/Graying_0/sources_1/ip/MultiplierBluex0d114/MultiplierBluex0d114.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MultiplierBluex0d114 || ORIG_REF_NAME==MultiplierBluex0d114} -quiet] -quiet

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/Graying_0/sources_1/ip/MultiplierGreenx0d587/MultiplierGreenx0d587.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MultiplierGreenx0d587 || ORIG_REF_NAME==MultiplierGreenx0d587} -quiet] -quiet

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/Graying_0/sources_1/ip/MultiplierRedx0d299/MultiplierRedx0d299.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MultiplierRedx0d299 || ORIG_REF_NAME==MultiplierRedx0d299} -quiet] -quiet
