# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
# IP: The module: 'rgb2dvi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
# IP: The module: 'rgb2dvi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/bowling233/Code/_repo/FPGA_edge_detection/vivado/vivado.gen/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
